-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 15:22:33 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema couch_safe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema couch_safe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `couch_safe` DEFAULT CHARACTER SET utf8 ;
USE `couch_safe` ;

-- -----------------------------------------------------
-- Table `USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USERS` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `profile_img` VARCHAR(100) NOT NULL,
  `user_type` ENUM('host', 'guest') NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `post_code` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `LISTINGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LISTINGS` (
  `listing_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `listing_img` VARCHAR(100) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `availability` MEDIUMTEXT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`listing_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `LISTINGS_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `USERS` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `RATINGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RATINGS` (
  `rating` INT(11) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `listing_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`listing_id`, `user_id`),
  INDEX `listing_id_idx` (`listing_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `RATINGS_listing_id`
    FOREIGN KEY (`listing_id`)
    REFERENCES `LISTINGS` (`listing_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `RATINGS_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `USERS` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
